export const KB_CHUNK_MAX_TOKENS = 900
export const KB_CHUNK_OVERLAP_TOKENS = 150
export const KB_DEFAULT_RETRIEVAL_LIMIT = 12
export const KB_DEFAULT_RETRIEVAL_THRESHOLD = 0.55
export const KB_MAX_CHUNKS_PER_SOURCE = 3
export const KB_CONTEXT_TOKEN_BUDGET = 10_000
export const KB_PROCESS_BATCH_SIZE = 5
